version: 2
updates:
    - package-ecosystem: npm
      directory: /
      versioning-strategy: increase
      schedule:
          interval: weekly
      reviewers:
          - perrin4869
      assignees:
          - perrin4869
